install.packages(c("nycflights13", "gapminder", "RColorBrewer",
                    "emmeans","mgcv","nlme","broom",
                    "tidybayes","statebins","sf","maptools",
                    "sp","rgeos","ggspatial","geofacet","misc3d",
                    "plot3D","magick","hexbin","treemapify",
                    "gridExtra", "rworldmap","ggmap","ggthemes",
                    "ggfortify","ggridges","ggrepel","ggforce",
                    "patchwork","lubridate","forcats","stringr",
                    "purrr","readr","tidyr","tibble","tidyverse",
                    "dplyr","ggplot2","colorspace","rjson","class",
                    "rprojroot","estimability","ggstance","rstudioapi",
                    "farver","ggfittext","svUnit","mvtnorm","xml2",
                    "knitr", "polyclip","jsonlite","png","pngjsonlite",
                    "httr", "backports", "assertthat","Matrix","lazyeval",
                    "cli","tweenr","prettyunits","htmltools",
                    "htmlwidgets","coda","gtable","glue","Rcpp",
                    "cellranger","imguR","xfun","rvest","MASS",
                    "scales","hms","yaml","stringi","e1071","spData",
                    "rlang","pkgconfig","bitops",
                    "geogrid","evaluate","lattice","tidyselect","plyr",
                    "magrittr","R6", "generics","DBI","pillar","haven",
                    "foreign","withr","units","modelr","crayon",
                    "arrayhelpers", "progress","jpeg","rnaturalearth",
                    "readxl","digest","classInt","tinytex", "xtable", "munsell",
                    "ggplot2movies", "base64enc","rmarkdown", 
                    "tikzDevice","scales","bookdown","remotes",
                    "FactoMineR","tidymodels","vcd"," lwgeom",
                    "gridGraphics","caret", "repr", "GGally",
                    "IRdisplay", "pdbZMQ", "argparse", "vegan", "ape","doBy",
                   "extrafont", "showtext","reshape2", "ggalt", "factoextra", "IRdisplay", "svglite",
                   "cowplot", "KODAMA", "ComplexHeatmap", "dendextend", "NbClust", "rfPermute", 
                   "FSA", "matrixStats"
                  ))

tinytex::install_tinytex()
tinytex:::install_yihui_pkgs()
tinytex::tlmgr_install(c('psnfss', 'metafont', 'mfware', 'inconsolata', 'tex', 
                         'ae', 'parskip', 'listings', 'pgf', 'preview', 'grfext', 'epstopdf',
                        'standalone', 'luatex85', 'pgfplots', 'geometry', 'fancyhdr',
                         'amsmath', 'amssymb', 'hyperref', 'graphicx', 'xcolor', 'enumerate',
                         'enumitem', 'inputenc', 'fontenc', 'titling', 'longtable'))
tinytex::tlmgr_update() 
